export const modules: { code: string; name: string }[] = [
    { code: "CS1002", name: "Object-Oriented Programming" },
    { code: "CS1003", name: "Programming with Data" },
    { code: "CS1006", name: "Programming Projects" },
    { code: "CS1007", name: "Computer Systems Fundamentals" },
    { code: "CS2001", name: "Foundations of Computation" },
    { code: "CS2002", name: "Computer Systems" },
    {
        code: "CS2003",
        name: "The Internet and the Web: Concepts and Programming",
    },
    { code: "CS2006", name: "Advanced Programming Projects" },
    { code: "CS2101", name: "Foundations of Computation (Accelerated)" },
    { code: "CS3050", name: "Logic and Reasoning" },
    { code: "CS3052", name: "Computational Complexity" },
    { code: "CS3099", name: "Software Engineering Team Project" },
    { code: "CS3101", name: "Databases" },
    { code: "CS3102", name: "Data Communications and Networks" },
    { code: "CS3104", name: "Operating Systems" },
    { code: "CS3105", name: "Artificial Intelligence" },
    { code: "CS3106", name: "Human Computer Interaction" },
    { code: "CS3301", name: "Component Technology" },
    { code: "CS3302", name: "Data Encoding" },
    { code: "CS4098", name: "Minor Software Project" },
    { code: "CS4099", name: "Major Software Project" },
    { code: "CS4102", name: "Computer Graphics" },
    { code: "CS4103", name: "Distributed Systems" },
    { code: "CS4105", name: "Advanced Communication Networks and Systems" },
    { code: "CS4201", name: "Programming Language Design and Implementation" },
    { code: "CS4202", name: "Computer Architecture" },
    { code: "CS4203", name: "Computer Security" },
    { code: "CS4204", name: "Concurrency and Multi-Core Architectures" },
    { code: "CS4302", name: "Signal Processing: Sound, Image, Video" },
    { code: "CS4303", name: "Video Games" },
    { code: "CS4402", name: "Constraint Programming" },
    { code: "CS4796", name: "Joint Project (30cr)" },
    {
        code: "CS5001",
        name: "Object-Oriented Modelling, Design and Programming",
    },
    { code: "CS5002", name: "Programming Principles and Practice" },
    { code: "CS5003", name: "Masters Programming Projects" },
    { code: "CS5010", name: "Artificial Intelligence Principles" },
    { code: "CS5011", name: "Artificial Intelligence Practice" },
    { code: "CS5012", name: "Language and Computation" },
    { code: "CS5014", name: "Machine Learning" },
    { code: "CS5015", name: "Symbolic Artificial Intelligence" },
    { code: "CS5016", name: "Uncertainty in Artificial Intelligence" },
    { code: "CS5020", name: "Principles of Computer Communication Systems" },
    { code: "CS5030", name: "Software Engineering Principles" },
    { code: "CS5031", name: "Software Engineering Practice" },
    { code: "CS5032", name: "Critical Systems Engineering" },
    { code: "CS5033", name: "Software Architecture and Design" },
    { code: "CS5034", name: "Software Product and Project Management" },
    { code: "CS5035", name: "Software Quality" },
    {
        code: "CS5040",
        name: "Human Computer Interaction Principles and Methods",
    },
    { code: "CS5041", name: "Interactive Software and Hardware" },
    { code: "CS5042", name: "User-Centred Interaction Design" },
    { code: "CS5044", name: "Information Visualisation" },
    { code: "CS5052", name: "Data-Intensive Systems" },
    { code: "CS5055", name: "Data Ethics and Privacy" },
    {
        code: "CS5098",
        name: "Group Project and Dissertation in Computer Science",
    },
    { code: "CS5099", name: "Dissertation in Computer Science" },
    { code: "CS5103", name: "Web Technologies" },
    { code: "CS5199", name: "Individual Masters Project" },
    { code: "CS5201", name: "Special Project for Research Engineers" },
    { code: "ID5059", name: "Knowledge Discovery and Datamining" },
    { code: "IS1901", name: "Information Technology 1" },
    { code: "IS5110", name: "Digital Heritage and Preservation" },
]
