name: Publish

on:
    workflow_dispatch:

jobs:
    build-chrome:
        name: Build Chrome extension
        timeout-minutes: 15
        runs-on: ubuntu-latest

        steps:
            - name: Check out code
              uses: actions/checkout@v4
              with:
                  fetch-depth: 2

            - name: Setup Bun environment
              uses: oven-sh/setup-bun@v1
              with:
                  bun-version: 0.7.0

            - name: Install dependencies
              run: bun install

            - name: Build Chrome
              run: bun run build

            - name: Zip Chrome extension
              run: |
                  cd dist
                  zip -r ../chrome_extension.zip .

            - name: Upload Chrome extension artifacts
              uses: actions/upload-artifact@v4
              with:
                  name: better-studres-chrome
                  path: chrome_extension.zip

            - name: Publish to Chrome Web Store
              uses: fregante/setup-chrome-webstore@v1
              with:
                  client_id: ${{ secrets.CHROME_EXTENSION_CLIENT_ID }}
                  client_secret: ${{ secrets.CHROME_EXTENSION_CLIENT_SECRET }}
                  refresh_token: ${{ secrets.CHROME_EXTENSION_REFRESH_TOKEN }}
                  extension_id: kamnhbpjhhhjlbandgpngdnplledombg
                  source: chrome_extension.zip
              env:
                  WEBSTORE_CLIENT_ID: ${{ secrets.CHROME_EXTENSION_CLIENT_ID }}
                  WEBSTORE_CLIENT_SECRET: ${{ secrets.CHROME_EXTENSION_CLIENT_SECRET }}
                  WEBSTORE_REFRESH_TOKEN: ${{ secrets.CHROME_EXTENSION_REFRESH_TOKEN }}

    build-firefox:
        name: Build Firefox extension
        timeout-minutes: 15
        runs-on: ubuntu-latest

        steps:
            - name: Check out code
              uses: actions/checkout@v4
              with:
                  fetch-depth: 2

            - name: Setup Bun environment
              uses: oven-sh/setup-bun@v1
              with:
                  bun-version: 0.7.0

            - name: Install dependencies
              run: bun install

            - name: Build Firefox
              run: bun run build:firefox

            - name: Upload Firefox extension artifacts
              uses: actions/upload-artifact@v4
              with:
                  name: better-studres-firefox
                  path: dist/
